version: "3"

services:
  tours_backend_app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    volumes:
      - ./tours_backend_app:/app
    command: >
      sh -c "sleep 5 &&python manage.py makemigrations && python manage.py migrate && python manage.py runscript init_tours &&python manage.py runserver 0.0.0.0:3003"

    environment:
      - DB_HOST=db
      - DB_NAME=mydb-dev
      - DB_USER=admin
      - DB_PASS=password
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=mydb-dev
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data

  frontend:
    command : npm start
    container_name: front
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - db

volumes:
  db-volume: